from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUTS = ROOT / "outputs"
PAPER = ROOT / "paper"


REFERENCES = [
    r"\bibitem{fujishima1972} A. Fujishima and K. Honda, ``Electrochemical photolysis of water at a semiconductor electrode,'' \emph{Nature}, vol. 238, pp. 37--38, 1972, doi:10.1038/238037a0.",
    r"\bibitem{hoffmann1995} M. R. Hoffmann, S. T. Martin, W. Choi, and D. W. Bahnemann, ``Environmental applications of semiconductor photocatalysis,'' \emph{Chemical Reviews}, vol. 95, no. 1, pp. 69--96, 1995, doi:10.1021/cr00033a004.",
    r"\bibitem{pelaez2012} M. Pelaez, N. T. Nolan, S. C. Pillai, \emph{et al.}, ``A review on the visible light active titanium dioxide photocatalysts for environmental applications,'' \emph{Applied Catalysis B: Environmental}, vol. 125, pp. 331--349, 2012, doi:10.1016/j.apcatb.2012.05.036.",
    r"\bibitem{harris2020} C. R. Harris, K. J. Millman, S. J. van der Walt, \emph{et al.}, ``Array programming with NumPy,'' \emph{Nature}, vol. 585, pp. 357--362, 2020, doi:10.1038/s41586-020-2649-2.",
    r"\bibitem{virtanen2020} P. Virtanen, R. Gommers, T. E. Oliphant, \emph{et al.}, ``SciPy 1.0: fundamental algorithms for scientific computing in Python,'' \emph{Nature Methods}, vol. 17, pp. 261--272, 2020, doi:10.1038/s41592-019-0686-2.",
    r"\bibitem{hunter2007} J. D. Hunter, ``Matplotlib: A 2D graphics environment,'' \emph{Computing in Science \& Engineering}, vol. 9, no. 3, pp. 90--95, 2007, doi:10.1109/MCSE.2007.55.",
]


def latex_escape(value: object) -> str:
    text = str(value)
    replacements = {
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    return text


def write_markdown(summary: dict[str, object]) -> None:
    PAPER.mkdir(parents=True, exist_ok=True)
    best = summary["best_condition"]
    references = "\n".join(f"{i + 1}. {ref.replace(chr(92) + 'bibitem', '').strip()}" for i, ref in enumerate(REFERENCES))
    md = f"""# Response-Surface Constrained Kinetic Analysis of Visible-Light Dye Photodegradation on Nitrogen-Modified TiO2

**Synthetic English journal-style demonstration paper for Light Skills**

The canonical paper source is [`main.tex`](main.tex). `main.pdf` is compiled from LaTeX by `scripts/build_paper.py`.

## Abstract

This synthetic study demonstrates a reproducible environmental-chemistry workflow for visible-light dye photodegradation. A deterministic generator produced {summary['n_time_points']} UV-vis time records across {summary['n_conditions']} experimental conditions covering catalyst formulation, catalyst loading, pH, irradiance, and radical-scavenger perturbations. Pseudo-first-order fits recovered an optimum condition using {best['catalyst']} at {best['loading_g_L']:.2f} g L^-1, pH {best['pH']:.1f}, and {best['irradiance_mW_cm2']:.0f} mW cm^-2, with kobs = {best['k_obs_min-1']:.4f} min^-1 and an apparent half-life of {best['half_life_min']:.1f} min.

## Honesty boundary

All concentration traces are synthetic and generated by `scripts/generate_data.py`. The study demonstrates a science-style workflow package; it does not claim a real photocatalyst discovery.

## References

{references}
"""
    (PAPER / "main.md").write_text(md, encoding="utf-8")


def write_latex(summary: dict[str, object]) -> Path:
    PAPER.mkdir(parents=True, exist_ok=True)
    best = summary["best_condition"]
    top = summary["catalyst_summary"][0]
    rows = []
    for row in summary["catalyst_summary"]:
        rows.append(
            f"{latex_escape(row['catalyst'])} & {row['k_mean']:.4f} & {row['ci_low']:.4f} & {row['ci_high']:.4f} & {row['n']} \\\\"
        )
    table_rows = "\n".join(rows)
    refs = "\n".join(REFERENCES)
    tex = rf"""\documentclass[10pt]{{article}}
\usepackage[margin=0.72in]{{geometry}}
\usepackage[T1]{{fontenc}}
\usepackage{{amsmath}}
\usepackage{{graphicx}}
\usepackage{{booktabs}}
\usepackage{{caption}}
\usepackage[colorlinks=true,linkcolor=black,citecolor=black,urlcolor=blue]{{hyperref}}
\captionsetup{{font=small,labelfont=bf}}
\setlength{{\parskip}}{{0.45em}}
\setlength{{\parindent}}{{0pt}}

\title{{Response-Surface Constrained Kinetic Analysis of Visible-Light Dye Photodegradation on Nitrogen-Modified TiO$_2$}}
\author{{Light Skills Synthetic Science Demo}}
\date{{}}

\begin{{document}}
\maketitle

\begin{{abstract}}
This synthetic study demonstrates a reproducible environmental-chemistry workflow for visible-light dye photodegradation. A deterministic generator produced {summary['n_time_points']} UV-vis time records across {summary['n_conditions']} experimental conditions covering catalyst formulation, loading, pH, irradiance, and radical-scavenger perturbations. Pseudo-first-order fits recovered an optimum condition using {latex_escape(best['catalyst'])} at {best['loading_g_L']:.2f} g L$^{{-1}}$, pH {best['pH']:.1f}, and {best['irradiance_mW_cm2']:.0f} mW cm$^{{-2}}$, with $k_\mathrm{{obs}}={best['k_obs_min-1']:.4f}$ min$^{{-1}}$ and an apparent half-life of {best['half_life_min']:.1f} min. The paper is a workflow demonstration only: it does not claim a real photocatalyst discovery.
\end{{abstract}}

\textbf{{Honesty boundary.}} All concentration traces are synthetic and generated by the repository script. The package demonstrates a science-style workflow: data, analysis, figures, references, manuscript, LaTeX source, PDF, and preview.

\section{{Introduction}}
Semiconductor photocatalysis is a long-running route for light-driven environmental remediation~\cite{{fujishima1972,hoffmann1995,pelaez2012}}. A realistic computational demonstration should include time-resolved concentration traces, kinetic fitting, design-factor response surfaces, diagnostics, and mechanistic perturbation. This project uses that structure to showcase Light Skills without inventing experimental evidence.

\begin{{figure}}[htbp]
\centering
\includegraphics[width=0.96\linewidth]{{../figures/figure1_kinetics.png}}
\caption{{Synthetic visible-light degradation traces at the high-irradiance neutral-pH condition. Markers show replicate means and standard deviations; smooth lines are pseudo-first-order fits.}}
\label{{fig:kinetics}}
\end{{figure}}

\section{{Methods}}
Synthetic UV-vis absorbance records were generated for three catalyst formulations, five catalyst loadings, four pH levels, three irradiance settings, and a radical-scavenger panel. Rate constants were estimated by fitting
\[
\ln(C/C_0) = -k_\mathrm{{obs}}t + b
\]
for each condition. The response surface was summarized for N-TiO$_2$/H$_2$O$_2$ at fixed irradiance. Numerical analysis used NumPy, SciPy, and Matplotlib~\cite{{harris2020,virtanen2020,hunter2007}}.

\begin{{table}}[htbp]
\centering
\caption{{Bootstrap summaries over synthetic no-scavenger design conditions. Values are demonstration outputs, not measured catalyst performance.}}
\begin{{tabular}}{{lrrrr}}
\toprule
Catalyst & Mean $k_\mathrm{{obs}}$ & 95\% CI low & 95\% CI high & $n$ \\
\midrule
{table_rows}
\bottomrule
\end{{tabular}}
\label{{tab:catalysts}}
\end{{table}}

\section{{Results}}
The response surface selected {latex_escape(best['catalyst'])} near neutral pH and intermediate catalyst loading as the fastest simulated condition. The top catalyst-family mean was {latex_escape(top['catalyst'])} with mean $k_\mathrm{{obs}}={top['k_mean']:.4f}$ min$^{{-1}}$. The analysis is intentionally framed as a synthetic benchmark so that the artifact demonstrates a complete science workflow without overstating evidence.

\begin{{figure}}[htbp]
\centering
\includegraphics[width=0.78\linewidth]{{../figures/figure2_response_surface.png}}
\caption{{Response surface for fitted $k_\mathrm{{obs}}$ under N-TiO$_2$/H$_2$O$_2$ at fixed irradiance. The surface is generated from synthetic data.}}
\label{{fig:surface}}
\end{{figure}}

\begin{{figure}}[htbp]
\centering
\includegraphics[width=0.95\linewidth]{{../figures/figure3_diagnostics.png}}
\caption{{Kinetic fitting diagnostics. Left: fitted vs generator rate constants. Right: residual distribution.}}
\label{{fig:diagnostics}}
\end{{figure}}

\section{{Mechanistic Perturbation}}
The radical-scavenger panel is included to mimic a common mechanistic check in photocatalysis papers. In the synthetic generator, IPA causes the strongest activity loss, followed by BQ and EDTA. This ordering is scripted and should not be read as real mechanistic evidence.

\begin{{figure}}[htbp]
\centering
\includegraphics[width=0.74\linewidth]{{../figures/figure4_scavenger_effects.png}}
\caption{{Synthetic scavenger sensitivity under the selected condition. Activity is normalized to the no-scavenger control.}}
\label{{fig:scavenger}}
\end{{figure}}

\section{{Reproducibility and Limitations}}
Run \texttt{{python scripts/run\_all.py}} to regenerate the full project. A real English-journal submission would require actual experiments, instrument calibration metadata, replicate planning, uncertainty analysis, raw spectra, material characterization, and independent domain review. This artifact is a showcase of workflow shape and publication packaging.

\begin{{thebibliography}}{{9}}
{refs}
\end{{thebibliography}}

\end{{document}}
"""
    tex_path = PAPER / "main.tex"
    tex_path.write_text(tex, encoding="utf-8")
    print(f"Wrote {tex_path}")
    return tex_path


def compile_latex(tex_path: Path) -> None:
    latexmk = shutil.which("latexmk")
    pdflatex = shutil.which("pdflatex")
    if latexmk:
        subprocess.run(
            [latexmk, "-pdf", "-interaction=nonstopmode", "-halt-on-error", tex_path.name],
            cwd=tex_path.parent,
            check=True,
        )
    elif pdflatex:
        for _ in range(2):
            subprocess.run(
                [pdflatex, "-interaction=nonstopmode", "-halt-on-error", tex_path.name],
                cwd=tex_path.parent,
                check=True,
            )
    else:
        raise RuntimeError("No LaTeX compiler found. Install MiKTeX, TeX Live, or TinyTeX.")
    for suffix in (".aux", ".fdb_latexmk", ".fls", ".log", ".out"):
        aux = tex_path.with_suffix(suffix)
        if aux.exists():
            aux.unlink()
    print(f"Wrote {tex_path.with_suffix('.pdf')}")


def main() -> None:
    summary = json.loads((OUTPUTS / "analysis_summary.json").read_text(encoding="utf-8"))
    write_markdown(summary)
    tex_path = write_latex(summary)
    compile_latex(tex_path)


if __name__ == "__main__":
    main()
